### ISSUE TITLE
Error when subscribing to  node via my bot instance

### ISSUE THREAD

**Issue by skotze** [threefoldfoundation/node-status-bot#10]
Hi

After having started the bot, whenever I try to subscribe to a node the bot throws this:

'''1 chats and 0 subscribed users
2024-07-12 21:06:52,675 - root - ERROR - Failed to fetch node info
Traceback (most recent call last):
  File "/home/stephan/node-status-bot/node-status-bot.py", line 561, in subscribe
    if node_used_farmerbot(con, node_id):
  File "/home/stephan/node-status-bot/node-status-bot.py", line 343, in node_used_farmerbot
    result = con.execute("SELECT 1 FROM PowerStateChanged WHERE node_id=? AND state='Down'", (node_id,)).fetchone()
sqlite3.OperationalError: no such table: PowerStateChanged
'''
Is there a missing step in the documentation to DDL the database? or is something else going on?

**Comment by skotze** [comment]
as a quick check, using sqlite3 dmnd line on the created db file and running 'sqlite> SELECT * FROM sqlite_master WHERE type='table';'
Returns nothing. 

When is the schema created?

**Comment by scottyeager** [comment]
Hi @skotze,

Sorry for the slow reply here. I'm not used to anyone but me opening issues on this repo :slightly_smiling_face: 

With v2 of the bot, it's now a two part deployment. The "ingester" found in `ingester.py` is responsible for setting up and pushing data into the database. The old repo README said a bit about this but didn't include clear directions.

I have just updated the README with full instructions for operating v2 of the bot. Please let me know if it's sufficient for you or if you run into any issues.

**Comment by scottyeager** [comment]
This has been resolved completely in recently merged changes. The bot will now create the relevant tables if they aren't present on startup.
